import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <h1 className="text-5xl text-center p-8 bg-blue-500 text-white">
            Hello
          </h1>
        </header>
        {children}
        <footer>
          <p className="text-center p-4 bg-gray-200">
            © {new Date().getFullYear()} My Next.js App
          </p>
        </footer>
      </body>
    </html>
  );
}
