import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import HotspotSidebar from "./components/HotspotSideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-screen h-screen overflow-hidden flex flex-col`}
      >
        <div className="flex flex-col h-full">
          <header className="bg-white shadow sticky top-0 z-50">
            <div className="w-full px-4 sm:px-6 lg:px-8">
              <div className="flex justify-between items-center h-16">
                {/* Left: Logo */}
                <div className="flex items-center space-x-2">
                  <Image
                    src="/logo.svg"
                    alt="HakkiPukka Logo"
                    width={60}
                    height={60}
                    className="rounded-full"
                  />
                  <Link href="/">
                    <span className="text-xl font-bold text-green-800">
                      HakkiPukka
                    </span>
                  </Link>
                </div>

                {/* Center: Search and Radius */}
                <div className="flex items-center space-x-2 flex-grow justify-center">
                  <input
                    type="text"
                    placeholder="Search..."
                    className="border border-gray-300 rounded px-2 py-1 w-1/2"
                  />
                  <select className="border border-gray-300 rounded px-2 py-1">
                    <option value="10">10 km</option>
                    <option value="25">25 km</option>
                    <option value="50">50 km</option>
                  </select>
                </div>

                {/* Right: Placeholder for future links or icons */}
                <div className="flex items-center space-x-2">
                  <a href="#" className="hover:text-blue-600">
                    Sign in
                  </a>
                </div>
              </div>
            </div>
          </header>
          <main className="flex-grow overflow-auto max-h-full">{children}</main>
          <footer className="bg-gray-200">
            <p className="text-center p-4">
              © {new Date().getFullYear()} HakkiPukka 🐦
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
